#!/bin/sh
#
# chkconfig: 2345 56 25
# description: planetflow slice initscript
#

. /etc/rc.d/init.d/functions

case "$1" in
    start)
        echo -n "starting the planetflow slice:"
	echo "pf" > /vsys/pfmount.in
        echo
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}"
        RETVAL=1
esac

exit $RETVAL
